version: '3.1'

services:
  api:
    image: api-feign-client-demo
    container_name: api-feign-client-demo
    ports:
      - 8282:8282
  client:
    image: client-feign-client-demo
    container_name: client-feign-client-demo
    depends_on:
      - api
    ports:
      - 8283:8283
    environment:
      API_URL: api:8282