version: '3.1'

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: api-feign-client-demo
    image: api-feign-client-demo
    ports:
      - 8282:8282
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: client-feign-client-demo
    image: client-feign-client-demo
    depends_on:
      - api
    ports:
      - 8283:8283
    environment:
      API_URL: api:8282
