services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: api-feign-client-demo
    image: api-feign-client-demo
    ports:
      - 18080:8080
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health-check"]
      interval: 1s
      timeout: 1s
      retries: 20
    environment:
      SERVER_PORT: 8080
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: client-feign-client-demo
    image: client-feign-client-demo
    depends_on:
      api:
        condition: service_healthy
    ports:
      - 18081:8080
    environment:
      API_SPAM_ENABLED: true
      API_URL: api:8080
      SERVER_PORT: 8080
