version: '3.1'

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: api-feign-client-demo
    image: api-feign-client-demo
    ports:
      - 18080:8080
    environment:
      server.port: 8080
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: client-feign-client-demo
    image: client-feign-client-demo
    depends_on:
      - api
    ports:
      - 18081:8080
    environment:
      API_URL: api:8080
      server.port: 8080
